// Code generated by protoc-gen-go-http-server.
// source: pb/strings.proto

package strings

import (
	"errors"
	"net/http"
	"strings"
)

func init() {
	defaultStringsHTTPServerOptions.rtr = &StringsRouter{}
}

type StringsRouter struct {
}

func (r *StringsRouter) Route(req *http.Request) (string, error) {
	path := strings.Split(strings.Trim(req.URL.Path, "/"), "/")

	// method: GET

	if len(path) == 2 && path[0] == "Strings" && path[1] == "ToLower" {
		if req.Method != "POST" {
			return "", errors.New("excepted POST method")
		}
		return path[1], nil
	}

	return "", errors.New("route is not found")
}
