// Code generated by protoc-gen-go-http-server.
// source: pb/strings.proto

package strings

import (
	"context"

	"github.com/doroginin/protobuf/protoc-gen-go-http-server/codec"
)

func init() {
	defaultStringsHTTPServerOptions.srv = &StringsServerImpl{}
	defaultStringsHTTPServerOptions.cdc = &codec.RESTCodec{}
}

type StringsServerImpl struct{}

func (s *StringsServerImpl) ToUpper(ctx context.Context, req *StringRequest) (*StringResponse, error) {
	// TODO: implement me
	return &StringResponse{}, nil
}

func (s *StringsServerImpl) ToLower(ctx context.Context, req *StringRequest) (*StringResponse, error) {
	// TODO: implement me
	return &StringResponse{}, nil
}
