// Code generated by protoc-gen-go-http-server.
// source: strings.proto

package strings

import (
	"context"
)

func init() {
	defaultStringsHTTPServerOptions.srv = &StringsServerImpl{}
}

type StringsServerImpl struct{}

func (s *StringsServerImpl) ToUpper(ctx context.Context, req *StringRequest) (*StringResponse, error) {
	// TODO: implement me
	return &StringResponse{}, nil
}

func (s *StringsServerImpl) ToLower(ctx context.Context, req *StringRequest) (*StringResponse, error) {
	// TODO: implement me
	return &StringResponse{}, nil
}
