// Code generated by protoc-gen-go-http-server.
// source: strings.proto

package strings

import (
	"context"
	"strings"
)

func init() {
	defaultStringsHTTPServerOptions.srv = &StringsServerImpl{}
}

type StringsServerImpl struct{}

func (s *StringsServerImpl) ToUpper(ctx context.Context, req *StringRequest) (*StringResponse, error) {
	return &StringResponse{Str: strings.ToUpper(req.Str)}, nil
}

func (s *StringsServerImpl) ToLower(ctx context.Context, req *StringRequest) (*StringResponse, error) {
	return &StringResponse{Str: strings.ToLower(req.Str)}, nil
}
