// Code generated by protoc-gen-go-http-server.
// source: pb/strings.proto

package strings

import (
	"net/http"
)

func (s *StringsHTTPServer) ToUpper(w http.ResponseWriter, r *http.Request) {
	defer r.Body.Close()
	in := StringRequest{}
	err := s.opts.cdc.ReadRequest(r, &in)
	if err != nil {
		s.opts.cdc.WriteError(w, err)
		return
	}
	resp, err := s.opts.srv.ToUpper(r.Context(), &in)
	if err != nil {
		s.opts.cdc.WriteError(w, err)
		return
	}
	s.opts.cdc.WriteResponse(w, resp)
}

func (s *StringsHTTPServer) ToLower(w http.ResponseWriter, r *http.Request) {
	defer r.Body.Close()
	in := StringRequest{}
	err := s.opts.cdc.ReadRequest(r, &in)
	if err != nil {
		s.opts.cdc.WriteError(w, err)
		return
	}
	resp, err := s.opts.srv.ToLower(r.Context(), &in)
	if err != nil {
		s.opts.cdc.WriteError(w, err)
		return
	}
	s.opts.cdc.WriteResponse(w, resp)
}
