package generator

import (
	"strings"
	"text/template"
)

var HandlerTemplate = &Template{
	FileName: "%s.pb.http.handler.go",
	Body: template.Must(template.New(`file`).Funcs(template.FuncMap{
		`lower`: strings.ToLower,
	}).Parse(`
// Code generated by protoc-gen-go-http-server.
// source: {{ .Source }}

package {{ .Package }}

import (
	"net/http"
)

{{ range $sIdx, $service := .Services }}

{{ range $hIdx, $handler := $service.Handlers }}
func (s *{{ $service.Name }}HTTPServer) {{ $handler.Name }}(w http.ResponseWriter, r *http.Request) {
    defer r.Body.Close()
	in := {{ $handler.In }}{}
	err := s.opts.cdc.ReadRequest(r, &in)
    if err != nil {
        s.opts.cdc.WriteError(w, err)
		return
    }
	resp, err := s.opts.srv.{{ $handler.Name }}(r.Context(), &in)
	if err != nil {
        s.opts.cdc.WriteError(w, err)
		return
	}
	s.opts.cdc.WriteResponse(w, resp)
}
{{ end }}
{{ end }}`))}