package generator

import (
	"text/template"
	"strings"
)

var SwaggerTemplate = &Template{
	FileName: "%s.pb.swagger.go",
	Body: template.Must(template.New(`file`).Funcs(template.FuncMap{
		"escape": func(s string) string { return strings.Replace(s, "`", "` + \"``\" + `", -1) },
	}).Parse(`
// Code generated by protoc-gen-go-http-server.
// source: {{ .Source }}

package {{ .Package }}

import (
	"net/http"
)

{{ range $sIdx, $service := .Services }}

func (s *{{ $service.Name }}HTTPServer) Swagger(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusOK)
	w.Write(_swagger)
}

{{ end }}

var _swagger = []byte(` + "`" + `{{ escape (.Fields.Swagger) }}` + `` + "`)" + `
`))}